# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e828a96c7e600c35d6befd7753f997f7dc2622fdb865168e18439dc7d7031564a8cb375f7e0aaf0a87b41e178b3cbbf8d92a89fd9ea2563e1e2e016e674f030

test:
  secret_key_base: 6f350a143e77780bbf7ee9cadf708aa54860c7dc42817321fea1a2a5bb02a7dd818a0e0173415ee113b6fd52f7b57e9e552c25dec6416ce4769b78c517e128cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
